{{- if eq (.Values.resetDatabase | toString) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "food.fullname" . }}-reset-database
  labels:
    {{- include "food.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "food.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ default (.Chart.AppVersion | replace "." "-") .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java",  "-jar", "app.jar", "fixtures:load"]
          env:
            - name: SPRING_JPA_HIBERNATE_DDLAUTO
              value: create
          envFrom:
            - configMapRef:
                name: {{ include "food.fullname" . }}
            - secretRef:
                name: {{ include "food.fullname" . }}
            - secretRef:
                name: database
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
{{- end }}
