apiVersion: v1
kind: Secret
metadata:
  name: {{ include "food.fullname" . }}
  labels:
    {{- include "food.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{- if not (empty $value) }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
